
spring:
  application:
    name: coupon-core
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://${db_address}:${db_prot}/${db_name}
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${db_username}
      password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${redis_host}
      port: ${redis_port}


