

server:
  port: 9000


logging:
  config: classpath:logback/logback-spring.xml
  level:
    root: info


spring:
  jpa:
    legacy-ad:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/legacy-ad
        username: root
        password: localpw
      properties:
        hibernate:
          hbm2ddl.auto: update
          show_sql: true
          physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy