
server:
  port: 8081


logging:
  config: classpath:logback/logback-srping.xml
  level:
    root: info

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test_db?useSSL=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  cassandra:
    keyspace-name: test_keyspace
    port: 9042
    contact-points: localhost
    schema-action: create_if_not_exists
    local-datacenter: datacenter1