

server:
  port: 9100

logging:
  config: classpath:logback/logback-spring.xml
  level:
    root: info


spring:
  jpa:
    legacy-ad:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/legacy-ad
        username: root
        password: localpw
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          hbm2ddl.auto: validate
          show_sql: true
          physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    recent-ad:
      hikari:
        jdbc-url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: localpw
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          hbm2ddl.auto: update
          show_sql: true
          physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  cloud:
    stream:
      binders:
        legacy-rabbit:
          type: rabbit
          environment:
            spring.rabbitmq:
              host: localhost
              port: 5672
              username: ruser
              password: localpw
              virtual-host: legacy
      bindings:
        legacyConsumer-in-0:
          binder: legacy-rabbit
          destination: legacy-topic
          group: migration
