version: '3'
services:
  logstash:
    image: 'docker.elastic.co/logstash/logstash:7.10.2'
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
