

server:
  port: 9100

logging:
  config: classpath:logback/logback-spring.xml
  level:
    root: info


spring:
  profiles:
    include: core
  cloud:
    stream:
      binders:
        legacy-rabbit:
          type: rabbit
          environment:
            spring.rabbitmq:
              host: localhost
              port: 35672
              username: ruser
              password: localpw
              virtual-host: legacy
      bindings:
        legacyConsumer-in-0:
          binder: legacy-rabbit
          destination: legacy-topic
          group: migration