services:
  cassandra:
    image: cassandra:4.1 # Cassandra 최신 버전 사용
    container_name: cassandra
    ports:
      - "9042:9042" # 노드간 클러스터 내부 통신
#      - "7001:7001" # 노드간 보안 통신에 사용
#      - "7000:7000" # CQL 클라이언트와 통신
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_CLUSTER_NAME=my-cluster
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_START_RPC=true
      - CASSANDRA_DC=my-datacenter
    volumes:
      - ./data:/var/lib/cassandra