

server:
  port: 2343


logging:
  config: classpath:logback/logback-srping.xml
  level:
    root: info

spring:
  datasource:
    url: jdbc:mariadb://${DB_Address}:${DB_Port}/${DB_Name}
    username: ${DB_Username}
    password: ${DB_Password}
    driverClassName: org.mariadb.jdbc.Driver
  cache:
    type: redis
  data:
    redis:
      host: ${Redis_Address}
      port: ${Redis_Port}
      repositories:
        enabled: false
      expire:
        defaultTime: 3600 # 1분