

server:
  port: 9000


logging:
  config: classpath:logback/logback-spring.xml
  level:
    root: info


spring:
  jpa:
    legacy-ad:
      hikari:
        jdbc-url: jdbc:mysql://192.168.0.22:3306/legacy-ad
        username: root
        password: localpw
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          hbm2ddl.auto: update
          show_sql: true
          physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  cloud:
    stream:
      binders:
        legacy-rabbit:
          type: rabbit
          environment:
            spring.rabbitmq:
              host: localhost
              port: 5672
              username: ruser
              password: localpw
              virtual-host: legacy
      bindings:
        legacy-rabbit-out:          # Binding Name
          binder: legacy-rabbit     # Binder Name
          destination: legacy-topic # Exchange