services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_DATABASE: test_db
      MYSQL_REPLICATION_MODE: master
      MYSQL_REPLICATION_USER: replica_user
      MYSQL_REPLICATION_PASSWORD: replica_password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-conf:/etc/mysql/conf.d
networks:
  mysql-network:
    driver: bridge