services:
  featureflag-app:
    image: registry.gitlab.com/mason14/docker-image-store:featureflag-service
    networks:
      - featureflag_network
    ports:
      - "8080:8080"
    environment:
      - FEATUREFLAG_ENGINE_HOST=featureflag-engine
      - FEATUREFLAG_ENGINE_PORT=8013


  featureflag-engine:
    image: ghcr.io/open-feature/flagd:latest
    command: start --uri file:./etc/flagd/v1_example_flags.json
#    command: start  --uri https://raw.githubusercontent.com/open-feature/flagd/main/samples/example_flags.flagd.json
    volumes:
      - ./flagd:/etc/flagd
    networks:
      - featureflag_network
    stdin_open: true
    tty: true
    ports:
      - "8013:8013"
networks:
  featureflag_network:
    driver: bridge