spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=Asia/Seoul
    username: root
    password: localpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      uri: mongodb://rootuser:1234@localhost:27017/campus?authSource=admin
    redis:
      host: localhost
      port: 6379
    elasticsearch:
      host: localhost
      port: 9200


external-server:
  metadata:
    url: http://localhost:8088