services:
  redis-slave1:
    image: redis:7.2-alpine
    container_name: redis-slave1
    ports:
      - "6380:6379"
    command: ["redis-server", "--slaveof", "192.168.219.104", "6379"]
    volumes:
      - ./data:/data

  sentinel1:
    image: redis:7.2-alpine
    container_name: redis-sentinel1
    ports:
      - "26380:26379"
    command:
      - redis-sentinel
      - /etc/redis/sentinel.conf
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf

volumes:
  redis-slave1-data: