services:
  redis-slave:
    image: redis:7.2-alpine
    container_name: redis-slave
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICA_IP=192.168.0.138
    volumes:
      - ./data:/data
    command: ["redis-server", "--replicaof", "192.168.0.138", "6379", "--replica-announce-ip", "192.168.0.20"]
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge